### ISSUE TITLE
Docker iteratechh user

### ISSUE THREAD

**Issue by jpvincent** [iteratec/OpenSpeedMonitor#29]
I found (via google) another repository for the OSM docker image :
https://hub.docker.com/r/iteratechh/openspeedmonitor/

is it official in any way ?
could it be someone trying to squat your user on the docker hub ?

Cheers

**Comment by nilskuhn** [comment]
[This](https://hub.docker.com/r/iteratec/openspeedmonitor/) is the official image. You will find a `latest` tag and a tag for each stable version there.

[Here](https://github.com/iteratec/OpenSpeedMonitor/blob/master/docker/docker-compose.yml) you can find a compose file using the official image. The compose file also runs containers for osm detail analysis microservice. That service facilitates interactive analysis of waterfalls resource data. [Here](https://demo.openspeedmonitor.org/detailAnalysis/show?_action_show=Show&selectedTimeFrameInterval=259200&from=2017-12-03T23%3A00%3A00.000Z&to=2017-12-07T22%3A59%3A00.000Z&selectedFolder=23&selectedPages=20&selectedPages=24) you can see that dashboard in action. It loads a while for the data initially because it is implemented with [dc.js](https://dc-js.github.io/dc.js/) which needs a little data initialization prior interactive data investigation is possible.

We own the `iteratechh` account too, but it's OpenSpeedMonitor image it's no longer actively maintained.
