### ISSUE TITLE
Page could not be deleted

### ISSUE THREAD

**Issue by coderDem** [iteratec/OpenSpeedMonitor#9]
Hello,

I would like to delete some testdata and pages from osm.
But if I try to delete the Page I get the error that the page could not be deleted.
How it is possible to delete the data right from osm?

best regards

**Comment by nilskuhn** [comment]
Hi,

it's because of the relations in underlying database. See [data model](https://raw.githubusercontent.com/wiki/IteraSpeed/OpenSpeedMonitor/images/20140918_osm_data_model_core.png) for details. We don't have cascading deletion on dependent domains. So for pages you have to delete all MeasuredEvents which depend on the page you want to delete. Unfortunately you will have to delete all EventResults that depend on the MeasuredEvent before you can delete the MeasuredEvent and the page :( 

So that's not really the way to go, cause EventResults you would have to delete in database, manually. In actual HEAD we added functionality to delete whole Jobs. That will delete the following Job-associated domains, also: 

* JobResults
* EventResults
* HttpArchives (don't get written by now)

So after deleting a job you will be able to delete MeasuredEvents and Pages via crud-gui. Instead of deleting MeasuredEvents and pages we could also introduce an active flag and hide inactive objects in dashboards. The Events and pages are no mass data problem like EventResults so leave them in db and hide them in view would work and would enable hiding without deletion of associated Jobs/Results. 

What do you think?

btw

We are also adding possibility to delete data older x months nightly via quartz job, where count of months x is configurable. That isn't quite implemented, yet. But should be available this week.

**Comment by coderDem** [comment]
Hey,

thank you for the reply. I managed to delete the pages with the routine above throw the MySQL Workbench. I think the best way is an routine if you delete the an Page you delete the script_page. That I would show the user like: "If you delete the Page X you delete the script_page below.". If that is to complicated I would like to give the user a hint how to do it. Because errors like: "Page 3 could not be deleted" give the user no clue what actually the problem is.

cheers
